name: Directory test
on:
  push:
    branches:
      - main

jobs:
  dir:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: run test directory
        run: 'df -h --total'
      - name: spec list with fastfetch
        run: |
          sudo apt install ppa:zhangsongcui3371/fastfetch
          fastfetch

